### PR TITLE
feat: autofill attributes

### PR DESCRIPTION
**Pull request by linuxdotexe**
I created an issue about the autofill attributes. This PR closes that issue (#38). I added attributes that make the browser give autofill suggestions for the login and signup pages. Here are screenshots before the change:

before

Here are screenshots after I added those attributes:

after

I hope this is a helpful change.

### CODE REVIEW

**Comment by linuxdotexe** [comment]
Hey! Can someone respond to this PR? It's nearly been 20 days...

**Review by gewenyu99 — APPROVED** [review]
LGTM

**Comment by gewenyu99** [comment]
Merging.

**Comment by linuxdotexe** [comment]
Thanks a lot!

**Pull request merged**
